/**
 * GENERATED by the seed-pin re-anchor helper — DO NOT HAND-EDIT.
 * Verify anchors / re-anchor after an rng-order change:
 *
 *   node --disable-warning=ExperimentalWarning --import ./tools/register.mjs packages/harness/src/reanchor.ts [--write]
 *
 * Seed-pin anchors: the seeds (and scout-derived floors) whose streams
 * currently exhibit the phenomena the consuming tests assert. Anchors are
 * rng-order-COUPLED by design (AGENTS.md §1.2: adding, removing, or
 * reordering any rng call reshuffles every stream), so a legitimate
 * rng-order change may strand them — the consuming tests' vacuity floors
 * then trip LOUDLY, and the fix is a re-scout, never a weakened floor
 * (AGENTS.md §1.6; issue #50). The helper re-scouts stranded anchors per
 * each pin's documented doctrine, rewrites this file, and re-runs the
 * consuming tests; review the diff it produces. The diff of this file IS
 * the re-anchor record (register W54/W56 tracked these re-anchors by hand).
 */

export const SEED_PINS = {
  "meta": {
    "generatedAt": "2026-08-01",
    "note": "Anchors consumed by pbp.test.ts (pbpGame). Assertions and floors live in the test; this file only answers which seed currently exhibits the pinned phenomenon."
  },
  "pbpGame": {
    "seed": "pbp-35",
    "provenance": "re-anchored 2026-08-01 by the helper (scanned pbp-1..64; picked the lead/tie-richest stream: 42 moments). The M-37 floor is > 0 lead/tie moments."
  }
};
