/**
 * GENERATED by the seed-pin re-anchor helper — DO NOT HAND-EDIT.
 * Verify anchors / re-anchor after an rng-order change:
 *
 *   node --disable-warning=ExperimentalWarning --import ./tools/register.mjs packages/harness/src/reanchor.ts [--write]
 *
 * Seed-pin anchors: the seeds (and scout-derived floors) whose streams
 * currently exhibit the phenomena the consuming tests assert. Anchors are
 * rng-order-COUPLED by design (AGENTS.md §1.2: adding, removing, or
 * reordering any rng call reshuffles every stream), so a legitimate
 * rng-order change may strand them — the consuming tests' vacuity floors
 * then trip LOUDLY, and the fix is a re-scout, never a weakened floor
 * (AGENTS.md §1.6; issue #50). The helper re-scouts stranded anchors per
 * each pin's documented doctrine, rewrites this file, and re-runs the
 * consuming tests; review the diff it produces. The diff of this file IS
 * the re-anchor record (register W54/W56 tracked these re-anchors by hand).
 */

export const SEED_PINS = {
  "meta": {
    "generatedAt": "2026-08-01",
    "note": "Anchors consumed by events.test.ts (evstreamPool), subs.test.ts (otseek, audit H-02), timeouts.test.ts (tocap), leakout.test.ts (leakout). Assertions and floors live in the tests; this file only answers which seeds currently exhibit the pinned phenomena."
  },
  "evstreamPool": {
    "regulation": "evstream-4",
    "overtime": "evstream-214",
    "provenance": "re-anchored 2026-08-01 by the helper (scanned evstream-1..240; the qualifying pair with the widest minimum floor headroom, 1.00x). evstream-4 — regulation; 1 def-won + 1 off-won jumps, 3 offensive fouls, 0 technicals, 2 violations, 1 replay reviews. evstream-214 — overtime; 3 def-won + 0 off-won jumps, 1 offensive fouls, 1 technicals, 2 violations, 2 replay reviews."
  },
  "otseek": {
    "seeds": [
      "otseek-35",
      "otseek-59",
      "otseek-126",
      "otseek-157",
      "otseek-162",
      "otseek-179"
    ],
    "provenance": "re-anchored 2026-08-01 by the helper (scanned otseek-0..179 of the 0..1200 ceiling, first 6 OT-reaching seeds — the H-02 doctrine; hand-anchor trail in the subs.test.ts header). 6/6 reach overtime at anchor; the test floor is >= 2."
  },
  "tocap": {
    "seeds": [
      "to-cap-2",
      "to-cap-4"
    ],
    "provenance": "re-anchored 2026-08-01 by the helper (scanned to-cap-1..32, first 2 qualifying). Qualification per seed: the control arm (late cap 2) spends >= 1 late-Q4 timeout, the 0-cap arm spends none there and still spends >= 4 in Q1-Q3."
  },
  "leakout": {
    "scout": {
      "stagedTransition": 24,
      "liveTransition": 148,
      "stagedOpener": 1,
      "liveOpener": 0
    },
    "floors": {
      "stagedVacuityMin": 15,
      "liveRiseMin": 40,
      "openerSlack": 6
    },
    "provenance": "floors hand-derived at the staged landing (scout over the fixed pool leakout-1..24: staged arm 24 transition leak signatures, flipped arm 148 — leakout.test.ts header). Safety shape per that header: vacuity ~60% of the staged scout, rise ~1/3 of the gap; openerSlack is FEEL and carries unchanged across re-anchors."
  }
};
