/**
 * GENERATED by the seed-pin re-anchor helper — DO NOT HAND-EDIT.
 * Verify anchors / re-anchor after an rng-order change:
 *
 *   node --disable-warning=ExperimentalWarning --import ./tools/register.mjs packages/harness/src/reanchor.ts [--write]
 *
 * Seed-pin anchors: the seeds (and scout-derived floors) whose streams
 * currently exhibit the phenomena the consuming tests assert. Anchors are
 * rng-order-COUPLED by design (AGENTS.md §1.2: adding, removing, or
 * reordering any rng call reshuffles every stream), so a legitimate
 * rng-order change may strand them — the consuming tests' vacuity floors
 * then trip LOUDLY, and the fix is a re-scout, never a weakened floor
 * (AGENTS.md §1.6; issue #50). The helper re-scouts stranded anchors per
 * each pin's documented doctrine, rewrites this file, and re-runs the
 * consuming tests; review the diff it produces. The diff of this file IS
 * the re-anchor record (register W54/W56 tracked these re-anchors by hand).
 */

export const SEED_PINS = {
  "meta": {
    "generatedAt": "2026-08-01",
    "note": "Anchors consumed by events.test.ts (evstreamPool), subs.test.ts (otseek, audit H-02), timeouts.test.ts (tocap), leakout.test.ts (leakout). Assertions and floors live in the tests; this file only answers which seeds currently exhibit the pinned phenomena."
  },
  "evstreamPool": {
    "regulation": "evstream-182",
    "overtime": "evstream-168",
    "provenance": "anchored 2026-08-01 by hand at the #74 amended-dose landing (re-scanned evstream-1..300, slot 1 held; re-anchor trail in the events.test.ts header). Slot semantics: one regulation game rich in the flow vocabulary + one overtime game; the pooled floors are enumerated in reanchor.ts EVSTREAM_FLOORS."
  },
  "otseek": {
    "seeds": [
      "otseek-60",
      "otseek-126",
      "otseek-157",
      "otseek-196",
      "otseek-205",
      "otseek-209"
    ],
    "provenance": "anchored 2026-08-01 by hand at the #74 amended-dose landing (re-scanned otseek-0..300, 7 OT seeds found, list carries the first six; eighth re-anchor — trail in the subs.test.ts H-02 header). Doctrine: 6/6 reach overtime at anchor; the test floor is >= 2 so reshuffle luck has headroom."
  },
  "tocap": {
    "seeds": [
      "to-cap-1",
      "to-cap-7"
    ],
    "provenance": "anchored by hand at the #74 amended-dose landing (scouted to-cap-1..16, picked 1 and 7, control late-Q4 counts 4 and 3 — timeouts.test.ts header). Qualification per seed: the control arm (late cap 2) spends >= 1 late-Q4 timeout, the 0-cap arm spends none there and still spends >= 4 in Q1-Q3."
  },
  "leakout": {
    "scout": {
      "stagedTransition": 24,
      "liveTransition": 148,
      "stagedOpener": 1,
      "liveOpener": 0
    },
    "floors": {
      "stagedVacuityMin": 15,
      "liveRiseMin": 40,
      "openerSlack": 6
    },
    "provenance": "floors hand-derived at the staged landing (scout over the fixed pool leakout-1..24: staged arm 24 transition leak signatures, flipped arm 148 — leakout.test.ts header). Safety shape per that header: vacuity ~60% of the staged scout, rise ~1/3 of the gap; openerSlack is FEEL and carries unchanged across re-anchors."
  }
};
